# Generated by Django 5.1.6 on 2025-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room_capacity', models.PositiveIntegerField()),
                ('projector_availability', models.BooleanField()),
            ],
        ),
    ]
